repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      # list of supported hooks: https://pre-commit.com/hooks.html
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files

  - repo: https://github.com/cmhughes/latexindent.pl
    rev: V3.19
    hooks:
      - id: latexindent
        args: [-l, -m, -s, -w]
